version: 2.1

workflows:
  main:
    jobs:
      - flow-deploy-sast:
          context: Conviso #has an env var called FLOW_API_KEY

jobs:
 flow-deploy-sast: 
    docker: 
      - image: "convisoappsec/flowcli:1.2.1"
    environment:
      FLOW_PROJECT_CODE: "u1oW48zMhwkJ_QD-"
      FLOW_API_KEY: $FLOW_API_KEY
      FLOW_API_URL: $FLOW_API_URL
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: deploy
          command: flow deploy create -f env_vars with values > created_deploy_vars
      - run: 
          name: sast
          command: |
            source created_deploy_vars
            flow sast run \
            --start-commit "$FLOW_DEPLOY_PREVIOUS_VERSION_COMMIT" \
            --end-commit "$FLOW_DEPLOY_CURRENT_VERSION_COMMIT"  
